### PR TITLE
Optimize definitions call

### PR DESCRIPTION
**Pull request by fkroockmann**
Optimize time ~ 1s to ~150ms

### CODE REVIEW

**Comment by eric-chau** [comment]
@fkroockmann can you explain me a bit more about this optimization please? I don't really get how it can drop from `1s` to `150ms` cause it seems that you just moved the code from `ClassContentManager` into `ClassContentController`.

**Comment by eric-chau** [comment]
This move also mean that the result of `::getAllClassContentClassnames()` is not anymore in cache so we have to compute it on every call.

**Comment by crouillon** [comment]
:+1:

**Comment by fkroockmann** [comment]
With many classcontent like 300 for big project, the loop take min 600 ms.
I cache the call in db and the loop then

**Comment by eric-chau** [comment]
Ok it's about the loop inside `ClassContentController::getClassContentDefinitionsByCategory()`. Nice catch, thank you :+1:

**Pull request merged**
