### PR TITLE
Resolved #11 - Updated nested nodes storage

### LINKED ISSUE #11: Updating nested nodes storage
Due to performance issue, nested nodes have to be stored in a new table 'section'.

Every page in BackBee will join a section row which will be the tree anchor for the website.

### PR DESCRIPTION
**Pull request by mickaelandrieu**
- [ ] To do
    - [x] Update NestedNode\Section
    - [x] Update NestedNode\Page
    - [ ] PageQueryBuilder does not extend NestedNodeQueryBuilder
    - [ ] Add PageQueryBuilder helpers

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
HI @crouillon, what is the status of this pull request ?

**Comment by mickaelandrieu** [comment]
ping @crouillon don't forget this one ;)

**Comment by eric-chau** [comment]
@mickaelandrieu, what about closing this PR?

**Comment by mickaelandrieu** [comment]
@eric-chau it's up to @crouillon :)

**Pull request closed without merging**
