### PR TITLE
[RFR] [Rest] #176 changed classcontent's category route pattern

### PR DESCRIPTION
**Pull request by eric-chau**
Currently, to get all classcontent's categories:

``/rest/{version}/classcontent/category``

And to get classcontent's specific category:

``/rest/{version}/classcontent/category/{id}``

This PR change these patterns:

- from ``/rest/{version}/classcontent/category`` to ``/rest/{version}/classcontent-category``
- from ``/rest/{version}/classcontent/category/{id}`` to ``/rest/{version}/classcontent-category/{id}``

These changes occur to avoid conflict with __get classcontent by type pattern__: ``/rest/{version}/classcontent/{type}``

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Wait before merge please.

**Comment by eric-chau** [comment]
ping @backbee/core-team:
- I added tests for ``Rest\Controller\ClassContentController::getCategoryAction`` and ``Rest\Controller\ClassContentController::getCategoryCollectionAction``
- I fixed travis warning log:
``PHP Strict standards:  Declaration of BackBee\Rest\Tests\Controller\UserControllerTest::signRequest() should be compatible with BackBee\Rest\Test\RestTestCase::signRequest(Symfony\Component\HttpFoundation\Request $request, BackBee\Security\User $user = NULL) in /home/travis/build/backbee/BackBee/Rest/Tests/Controller/UserControllerTest.php on line 416``
- I fixed ``Rest/Controller/AclController::postPermissionMapAction``.

I will merge it tomorrow.

**Comment by mickaelandrieu** [comment]
:+1: you improve BackBee day after day !

**Comment by ndufreche** [comment]
:+1:

**Comment by eric-chau** [comment]
Bouhh you merged my PR! :P

**Pull request merged**
