### PR TITLE
[Rewriting] updated the way we rewrite page's url

### PR DESCRIPTION
**Pull request by eric-chau**
More details on issue #352. The process is also clearer. Also updated coding style.

### CODE REVIEW

**Comment by eric-chau** [comment]
At moment do not merge it.

**Comment by eric-chau** [comment]
@mickaelandrieu, @crouillon, I finally ended the ``page's url rewriting process`` and added tests.

**Comment by mickaelandrieu** [comment]
@eric-chau can I merge it ? this sounds good.

**Comment by eric-chau** [comment]
I want to do some more checks.

**Comment by eric-chau** [comment]
And the issue about PHP memory limit still not resolved. It is green cause this problem doesn't occur everytimes so i spammed the build until it pass for each PHP version. :/

**Comment by eric-chau** [comment]
Well, my last commit fixed the issue about PHP memory limit, I simply splitted phpunit's tests to run a new php's script for each component.

**Pull request merged**
