### PR TITLE
Added Result Cache driver implementation

### PR DESCRIPTION
**Pull request by mickaelandrieu**
We can now use the result query cache driver => http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/caching.html#result-cache

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
ping @eric-chau @crouillon can we find time to review pull requests ?

**Comment by mickaelandrieu** [comment]
@eric-chau is this contribution need more work or not ?

**Comment by eric-chau** [comment]
@mickaelandrieu I'm not able to tell you right know if it bring any improvement to the project so I can't merge it. I guess you don't have many times right now to add some test to prove the benefit of this.

**Comment by mickaelandrieu** [comment]
I don't know how to test it.  It's create files in cache folder but I didn't notice performance improvements...

**Comment by eric-chau** [comment]
Doctrine Result Cache requires a meticulous work on which result to cache and for how long. So at moment it's not in BackBee roadmap to integrate it. Thanks for your @mickaelandrieu. I close it.

**Pull request closed without merging**
