### PR TITLE
#186 - Do not store empty element content

### PR DESCRIPTION
**Pull request by crouillon**

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
All is well :) please squash your commits I will try to review this one tomorrow.

**Comment by crouillon** [comment]
@mickaelandrieu squashed and ready to be review

**Comment by mickaelandrieu** [comment]
@crouillon you have a git history duplicate issue, can you squash your commits ? ("merge" all your commits into one)

**Comment by crouillon** [comment]
hum strange, it's already squashed for me

**Comment by crouillon** [comment]
ok squashed, thanks to @mickaelandrieu

**Comment by mickaelandrieu** [comment]
:+1: thank you @crouillon !

**Pull request merged**
