### PR TITLE
fix broken link to backbee.com

### PR DESCRIPTION
**Pull request by Remo**

### CODE REVIEW

**Comment by fkroockmann** [comment]
Thanks @Remo :)

**Comment by mickaelandrieu** [comment]
I think we need to update the link from the website... ping @clementbonfils can you update the url ?

**Comment by mickaelandrieu** [comment]
ping @clementbonfils : can you update links in http;//www.backbee.com ? Also I saw some references to BackBuilder5

**Comment by mickaelandrieu** [comment]
ping @clementbonfils do you need an issue ?

**Pull request closed without merging**
