### PR TITLE
[RFR] Removed every references (routes, actions, listeners, etc.) to JsonRPC server

### PR DESCRIPTION
**Pull request by eric-chau**
Removed every routes, actions, listeners or any other reference to JsonRPC Server inside ``backbee/backbee``.

Also removed some codes of ``Application`` component  (to be more precise, ``Analytics``) which was removed by PR #377.

### CODE REVIEW

**Comment by eric-chau** [comment]
Review done with @crouillon. Ping @mickaelandrieu for review please :)

**Comment by mickaelandrieu** [comment]
:+1:

**Comment by eric-chau** [comment]
@mickaelandrieu, I rebased master with your fresh PR #392 and some of yours tests depends on ``bb_area`` firewall which is not used anymore. Do you see any potential issue by doing your tests with ``rest_api_area`` firewall?

**Comment by mickaelandrieu** [comment]
I think this will works.

**Comment by crouillon** [comment]
:+1:

**Pull request merged**
