### PR TITLE
Fixed Page serialisation publishing/archiving

### PR DESCRIPTION
**Pull request by mickaelandrieu**
* REST Page api now returns publishing/archiving dates in same format than created/modified.
* Added a simple test for PageControllerTest ``getAction``
This is resolution of this issue: https://github.com/backbee/BbCoreJs/issues/746

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
wtf

```
➜  backbee git:(fix-page-api) phpunit
PHPUnit 4.4.2 by Sebastian Bergmann.

Configuration read from /home/mickael/Projets/LPDigital/backbee-standard/vendor/backbee/backbee/phpunit.xml.dist

...............................................................  63 / 373 ( 16%)
............................................................... 126 / 373 ( 33%)
............................................................... 189 / 373 ( 50%)
............................................................... 252 / 373 ( 67%)
............................................................... 315 / 373 ( 84%)
..........................................................

Time: 51.05 seconds, Memory: 556.25Mb

OK (373 tests, 1523 assertions)
```

**Comment by eric-chau** [comment]
This may due to the bundle toolbar which is not up to date

**Comment by mickaelandrieu** [comment]
yes, I relaunch the build (maybe the toolbar bundle pull request wasnt merged in master atm)

**Comment by mickaelandrieu** [comment]
@eric-chau ok, found the bug and fixed here => https://github.com/backbee/ToolbarBundle/pull/59

**Comment by eric-chau** [comment]
Nice that you found out the bug.

**Pull request merged**
