### PR TITLE
[Perf] Added micro optimizations

### PR DESCRIPTION
**Pull request by mickaelandrieu**
This little patch make some functions more cacheable by the PHP compiler because it know that they are  native functions and not from the class they were used.

In some cases, PHP optimize them (is_*, defined(), strlen). As this patch can't break anything and may improve the performances, let's do it (http://www.slideshare.net/nikita_ppv/php-7-what-changed-internally-php-barcelona-2015).

### CODE REVIEW

**Comment by fkroockmann** [comment]
I not agree for add "\" before each native function :-1:

**Comment by eric-chau** [comment]
:+1:

**Comment by mickaelandrieu** [comment]
ping @crouillon what do you think ?

**Comment by mickaelandrieu** [comment]
branch conflicted:feel free to re-apply this improvements.

**Pull request closed without merging**
