### PR TITLE
fixing mediafolder rest getAction

### PR DESCRIPTION
**Pull request by hbaptiste**
fixing mediafolder rest getAction

### CODE REVIEW

**Comment by eric-chau** [comment]
:+1:

**Comment by mickaelandrieu** [comment]
this won't pass the tests, did you have tried on your own machine @hbaptiste ?

**Comment by eric-chau** [comment]
I think I know why it does not work. I will check it for you @hbaptiste

**Comment by eric-chau** [comment]
Oh dude, I didn't notice that you use ``::toArray`` inside ``MediaFolder::jsonSerialize`` method... we have to change it. I will do it with you @hbaptiste.

**Comment by mickaelandrieu** [comment]
Then i don't see why we need another ``jsonSerialize`` method as we already have this helpers in RestController, can you explain ?

**Comment by eric-chau** [comment]
This PR is replaced by PR #417.

**Pull request closed without merging**
