### PR TITLE
[WIP] - migrate to Symfony 2.6

### PR DESCRIPTION
**Pull request by mickaelandrieu**
(REFS  #308)

Steps before a complete migration to Symfony 2.7 components, an exhaustive tasks list is available here: https://gist.github.com/mickaelandrieu/5211d0047e7a6fbff925

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
pin @eric-chau, for now can we merge this pull request for Symfony 2.6, we use an unmaintained version of Symfony...

**Comment by eric-chau** [comment]
So you plan to create another PR to migrate our SF dependencies to 2.7?

**Comment by mickaelandrieu** [comment]
@eric-chau I think we will create many pull requests in order to migrate component by component.

Also, we need to find a way to update without any BC.

**Comment by eric-chau** [comment]
@mickaelandrieu next time you merge your commit dont forget to change your commit message please.

**Pull request merged**
