### PR TITLE
[Site] Add Serializer\Type for Site label and layouts

### PR DESCRIPTION
**Pull request by quentin-boulard**
I had some error in deserialize some contents and correct it with adding serializer type.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
:+1:  do you have time to complete a test to check the rendering from REST API comply to your needs ? 
Maybe here ? => https://github.com/backbee/BackBee/blob/master/Rest/Tests/Controller/SiteControllerTest.php#L178

**Comment by quentin-boulard** [comment]
Sorry but no I don't have time for this. I just add Serializer\type and name because you set the @Serializer\Expose without.

**Comment by mickaelandrieu** [comment]
It's not up to me to merge pull requests without tests :/

ping @eric-chau, @crouillon you decide.

**Comment by eric-chau** [comment]
:+1: ok @quentin-boulard. Before I merge it, can you tell what you get in layouts key of serialized site? Does the serializer also call serializer on layouts? In others words does layout data get well serialized too?

**Pull request closed without merging**
