### PR TITLE
[ClassContent] updated ClassContentManager::findOneByTypeAndUid and ClassContentController::getAction

### PR DESCRIPTION
**Pull request by eric-chau**
Updated ``BackBee\ClassContent\ClassContentManager::findOneByTypeAndUid`` to not trying to set draft if content is null.
Updated ``BackBee\Rest\Controller\ClassContentController::getAction`` to throw exception on not found content.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@eric-chau is this ready for merge ? (maybe some tests are required to check this update actualy do the job ? )

**Comment by eric-chau** [comment]
@mickaelandrieu I was about to resolve #344 into this PR. I will try to add tests too.

**Comment by eric-chau** [comment]
I will complete this PR soonly, we won't notice any error until we provide an invalid classcontent's uid so I have to fix it to also handle error cases.

**Comment by eric-chau** [comment]
ping @mickaelandrieu, this PR is over and resolve issue #344.

**Pull request merged**
