### PR TITLE
Removed deprecated class String uses from BackBee core

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Bumped utils 2.0 which is compatible with php7 and introduce ``StringUtils`` instead of ``String``.

### CODE REVIEW

**Comment by eric-chau** [comment]
Yeah, finally we do it =) thank you @mickaelandrieu :+1:

**Comment by MaverickWar** [comment]
Is this linked to my issue...


Whoops, looks like something went wrong.

1/1
ClassNotFoundException in install.php line 232:
Attempted to load class "StringUtils" from namespace "BackBee\Utils".
Did you forget a "use" statement for "Symfony\Component\Security\Core\Util\StringUtils"?
in install.php line 232

**Comment by mickaelandrieu** [comment]
@MaverickWar what version of BackBee do you use?  Please use the latest version from github or require at least the 1.1 instead or 1.0.

The docs are **still** outdated /c @SylvainLejarre

**Comment by MaverickWar** [comment]
yes I can confirm this is version 1.0

**Pull request merged**
