### PR TITLE
#201 - Rename IApplication to ApplicationInterface

### PR DESCRIPTION
**Pull request by JeremyGreaux**

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi,
can you use ```php-formatter`` commands on your commit as described in ```CONTRIBUTING.md`` file ?

Regards,

**Comment by mickaelandrieu** [comment]
:+1: tests pass and formatted.

Thank you @JeremyGreaux !

**Comment by eric-chau** [comment]
Please don't merge it too fast next time @mickaelandrieu, the merge message is not valid and a fixup is missing.
Thanks @JeremyGreaux for your contribution :+1:

**Comment by eric-chau** [comment]
Btw tests didn't passed.

**Comment by mickaelandrieu** [comment]
they did, I just merged before ``Formatting`` commit new build pass.

**Pull request merged**
