### PR TITLE
[Site] removed unused entities and its repositories #384

### PR DESCRIPTION
**Pull request by eric-chau**
More details in #384.

@crouillon, I also removed ``BackBee\Site\UserPreferences`` entity cause it seems not used, can you confirm it?

This PR brings nice improvements cause it remove two tables from database schema.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@eric-chau SIte metadata are not used inside SEO module ?

**Comment by eric-chau** [comment]
@mickaelandrieu SEO module use ``Page`` metadata, not ``Site`` one. If I get it right ``Site\Metadata`` was designed to act as generic metadata for pages that has not metadata but it is never used, confirmed by @crouillon.

**Comment by mickaelandrieu** [comment]
yes, I believe the actual behavior is:
* if you don't have any metadata for this page, BackBee use the Site's one

does this refactoring have an impact on metadata.yml configuration file in backbee-standart repository ?

**Comment by eric-chau** [comment]
No, ``Site`` metadata is currently NEVER used. If a page has no metadata BackBee will rely on ``metadata.yml``, can you confirm it @crouillon?

**Comment by crouillon** [comment]
I confirm all points
regarding UserPref, there will have to be manage by the toolbarBundle (by now, it stores some pop-in status and position)

**Pull request merged**
