### PR TITLE
creating isDebug helper

### PR DESCRIPTION
**Pull request by ndufreche**
creating isDebug helper

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Before all new additions, I want an installable package for 1.0.*.

I will only accepts bug fix since then /c @crouillon .

So, please focus on this (important) task.

**Comment by ndufreche** [comment]
Is an important add, it is for identify what type of javascript we have to use in toolbar-bundle and it's you @mickaelandrieu who say to put it in the php core...
see backbee/ToolbarBundle#43

**Comment by mickaelandrieu** [comment]
yes, I think this need to be pushed in BackBee, but I need an installable package for 1.0 since 2 weeks now, so I prefer you focus on it if you don't mind.

I can confirm this will be merged then.

**Comment by ndufreche** [comment]
Yes but I need it into backbee/ToolbarBundle#44

**Comment by mickaelandrieu** [comment]
Merged.

Thanks @ndufreche

**Comment by mickaelandrieu** [comment]
@ndufreche your next PR will be on backbee-standard to push bb-core-dist.
Until then, I will only accept bug fixes: consider PHP projects frozen.

**Pull request merged**
