### PR TITLE
Improved error rendering messages for ajax requests

### PR DESCRIPTION
**Pull request by mickaelandrieu**
REFS https://github.com/backbee/backbee-standard/issues/325

the idea is to make errors more usables **in debug mode** from Javascripts clients /c  @ndufreche

### CODE REVIEW

**Comment by ndufreche** [comment]
Currently Javascript request send an accept response type, it can better to use this header parameters.

`Accept:application/json`

**Comment by mickaelandrieu** [comment]
Hi,
header "Accept" is for request sent from Javascript, the response returned by BackBee have the good "Content-Type" header (https://github.com/symfony/HttpFoundation/blob/master/JsonResponse.php#L194).

What do you suggest ?

**Comment by ndufreche** [comment]
The "Accept" is set by the js to specify what type of "format" the response must have. Content-type is to specify what is the format content in the response.
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html chapter 14.1

I suggest you to use this parameter to know what "format" you need to respond and not respond in json to all ajax request.

**Comment by mickaelandrieu** [comment]
:+1: I have updated my pull request. ping @eric-chau what do you think ? Can you merge ?

**Comment by ndufreche** [comment]
:+1: thanks a lot :)

**Comment by mickaelandrieu** [comment]
@eric-chau Scrutinizer didn't be updated. Error fixed https://scrutinizer-ci.com/g/backbee/BackBee/inspections/a057ab52-c3a3-4eca-9570-808454ac9f00

**Pull request merged**
