### PR TITLE
[WIP] Added MediaControllerTest

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Hi,

* Added Security annotation on Media REST API
* Added MediaControllerTest class
* Added tests

Don't merge it.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@eric-chau did you have any idea to actualy persist and flush a class content ?

**Comment by eric-chau** [comment]
I don't really get your request, can you explain it again please?

**Comment by mickaelandrieu** [comment]
Of course, I want to create a new media using post rest call.

The issue is a Media need a content (https://github.com/mickaelandrieu/BackBee/blob/media-controller-rights/Rest/Controller/MediaController.php#L161) and I have some weird doctrine mapping issue when I try to create any Content.

**Comment by eric-chau** [comment]
Ok, let's take a look at it together tomorrow.

**Comment by eric-chau** [comment]
@mickaelandrieu PR #421 is now merged, take use of ``TestKernel`` and ``BackBeeTestCase`` and resolve your PR ;)

**Comment by mickaelandrieu** [comment]
I will for sure ;)  nice additions!

**Comment by mickaelandrieu** [comment]
I will never finish this pull request

**Pull request closed without merging**
