### PR TITLE
get the request from application

### PR DESCRIPTION
**Pull request by mickaelandrieu**
in ExceptionListener.

ping @eric-chau

### CODE REVIEW

**Comment by ndufreche** [comment]
:+1:

**Comment by eric-chau** [comment]
Hm why do you get the request object? It seems that you don't use it in the method block.

**Comment by mickaelandrieu** [comment]
@eric-chau I do in the `in_array` to check what kind of Response I need to send.

**Comment by eric-chau** [comment]
@mickaelandrieu my bad I didn't see it. :+1: thank you =)

**Pull request merged**
