### PR TITLE
Dispatch rest event onKernelController and onKernelResponse

### PR DESCRIPTION
**Pull request by fkroockmann**
If the controller extends AbstractRestController, an event is dispatched

For Request: 'rest.controllername.actionname.request'
For Response: 'rest.controllername.actionname.response'

### CODE REVIEW

**Comment by fkroockmann** [comment]
Wait before merge plz

**Comment by fkroockmann** [comment]
Ok it's already done in Frontcontroller::invokeAction.... :(

**Comment by mickaelandrieu** [comment]
NOOOOB

**Comment by eric-chau** [comment]
Yes I ported this feature to ``FrontController``. Previously it was only done for JsonRPC request.

**Pull request closed without merging**
