### PR TITLE
[bug] Removing bb5toolbar helper called in some templates

### PR DESCRIPTION
**Pull request by ndufreche**
Removing bb5toolbar helper called in some templates and transform some template in twig

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Thank you @ndufreche, but if you change the templates you need to update the configuration in ``Config\services\error.yml``.

Then, I can merge :)

**Comment by mickaelandrieu** [comment]
this now need a rebase :cat:

**Comment by eric-chau** [comment]
@ndufreche, can you rebase your branch and so we can merge it if it's resolved?

**Comment by mickaelandrieu** [comment]
@eric-chau this need a rebase *and* to declare the new templates in ``Config\services\error.yml`` :)

**Comment by eric-chau** [comment]
@mickaelandrieu I guess this PR is out of date right now? It seems that you resolved it with multiple PR into ``backbee/backbee``, ``backbee/backbee-standard``.

**Comment by mickaelandrieu** [comment]
@ndufreche @eric-chau also, is the ``addStyleSheet`` helper work this way ? We use the ``renderer->partial()``

**Comment by eric-chau** [comment]
The ``::addStyleSheet`` works same as ``::addHeaderScript`` which is effective only if you're rendering a page, not a content.

**Comment by eric-chau** [comment]
This PR is not up-to-date anymore, see #439.

**Pull request closed without merging**
