### PR TITLE
Fix json encode on scalar element

### PR DESCRIPTION
**Pull request by fkroockmann**
Currently when scalar is empty or string the json decode return null instead of return the current string.

I add test to check if the json_decode dont have error and if the json decode return null.

I propose to set null if json decode throw error cause if we keep the current value, serialize will be broken

Let me know @eric-chau @crouillon

### CODE REVIEW

**Comment by eric-chau** [comment]
@fkroockmann your PR is very interesting. You're right, `json_decode` convert `null` and empty string into null so it's a good idea to leave with the initial value if `json_decode` succeed with no errors.
For your second suggestion about set the value to `null`, unfortunately we cannot do it cause we will break the compatibility with data stored in old database.

**Comment by fkroockmann** [comment]
yes i have think about that, you are right, if the json decode throw an error we need to put the value to empty string, what do you think ?

**Comment by fkroockmann** [comment]
I understand, i let the old value if the json decode throw an error

**Comment by crouillon** [comment]
:+1: Thanks @fkroockmann

**Pull request merged**
